In [1]:
import json
with open("./dataset/json/mini_publaynat_mlp_len_veclen50.json") as f:
    dataset = json.load(f)

print("Пример, x:", dataset["x"][0])
print("Размер x:", len(dataset["x"][1]))
print("Пример, y:", dataset["y"][1])
print("Кол-во записей:", len(dataset["x"]))

Пример, x: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
Размер x: 50
Пример, y: 1
Кол-во записей: 4958


In [2]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score
import pickle 

In [3]:
keys = list(set(dataset["y"]))
Y_keys = dict()
for i, key in enumerate(keys):
    zeros = np.zeros((len(keys)))
    zeros[i] = 1
    Y_keys[key] = zeros
Y_keys
Y = np.array([Y_keys[yi] for yi in dataset["y"]] )
X = np.array(dataset["x"])

In [4]:
x1 = [x for i, x in enumerate(X) if Y[i][0] == 1]
y1 = [y[:3] for y in Y if y[0] == 1]
x2 = [x for i, x in enumerate(X) if Y[i][1] == 1]
y2 = [y[:3] for y in Y if y[1] == 1]
x3 = [x for i, x in enumerate(X) if Y[i][2] == 1]
y3 = [y[:3] for y in Y if y[2] == 1]

In [5]:
len(x3)

995

In [6]:
len_text = 955
len_header = 995
len_list = 995

X = x1[:len_text]+ x2[:len_header] + x3[:len_list]
Y = y1[:len_text]+ y2[:len_header] + y3[:len_list]


In [7]:
X_train, X_test, y_train, y_test = train_test_split(
    X, Y, test_size=0.2, random_state=42)

In [14]:
# Creating (MLP) classifier
clf = MLPClassifier(hidden_layer_sizes=(50, 40, 40, 30, 20), max_iter=1000,
                    random_state=42)

In [15]:
# Training the model
clf.fit(X_train, y_train)
# Making prediction
y_pred = clf.predict(X_test) 

In [16]:
# Determining Accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.2f}")

Accuracy: 0.62


In [17]:
# save the model 
filename = 'model-5.sav'
pickle.dump(clf, open(filename, 'wb')) 

In [84]:
clf.predict(X_test)

array([[0, 0, 1],
       [0, 0, 1],
       [1, 0, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 0, 1],
       [0, 0, 1],
       [1, 0, 0],
       [0, 1, 0]])

In [85]:
y_test

[array([0., 0., 1.]),
 array([0., 0., 1.]),
 array([1., 0., 0.]),
 array([0., 0., 1.]),
 array([1., 0., 0.]),
 array([0., 1., 0.]),
 array([1., 0., 0.]),
 array([1., 0., 0.]),
 array([0., 1., 0.]),
 array([0., 0., 1.]),
 array([0., 0., 1.]),
 array([1., 0., 0.]),
 array([0., 1., 0.])]